# Generated by Django 2.0.3 on 2018-05-23 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publications_bootstrap', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('publication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publications_bootstrap.Publication')),
            ],
            bases=('publications_bootstrap.publication',),
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Literature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('citations', models.ManyToManyField(related_name='literature_citation', to='project_structure.Citation')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Misc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('acronym', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('git_repo', models.URLField(blank=True)),
                ('shared_drive', models.URLField(blank=True)),
                ('citations', models.ManyToManyField(blank=True, to='project_structure.Citation')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('degree', models.CharField(choices=[('Ph.D.', 'Ph.D.'), ('M.S.', 'M.S.'), ('M.A.', 'M.A.'), ('B.S.', 'B.S.'), ('B.A.', 'B.A.')], max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='Title in Organization')),
                ('organization', models.CharField(blank=True, max_length=300)),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('active', models.BooleanField(default=True)),
                ('org_description', models.TextField(blank=True, verbose_name='Organization Description')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='prepared_by',
            field=models.ManyToManyField(related_name='publication_prepared_by', to='project_structure.Researcher'),
        ),
        migrations.AddField(
            model_name='publication',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='project_structure.Project'),
        ),
        migrations.AddField(
            model_name='project',
            name='researchers',
            field=models.ManyToManyField(to='project_structure.Researcher'),
        ),
        migrations.AddField(
            model_name='project',
            name='sponsors',
            field=models.ManyToManyField(to='project_structure.Sponsor'),
        ),
        migrations.AddField(
            model_name='misc',
            name='prepared_by',
            field=models.ManyToManyField(related_name='misc_prepared_by', to='project_structure.Researcher'),
        ),
        migrations.AddField(
            model_name='misc',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='project_structure.Project'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='prepared_by',
            field=models.ManyToManyField(related_name='meeting_prepared_by', to='project_structure.Researcher'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='project_structure.Project'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='project_attendees',
            field=models.ManyToManyField(related_name='project_attendees', to='project_structure.Researcher'),
        ),
        migrations.AddField(
            model_name='literature',
            name='prepared_by',
            field=models.ManyToManyField(related_name='literature_prepared_by', to='project_structure.Researcher'),
        ),
        migrations.AddField(
            model_name='literature',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='project_structure.Project'),
        ),
        migrations.AddField(
            model_name='data',
            name='prepared_by',
            field=models.ManyToManyField(related_name='data_prepared_by', to='project_structure.Researcher'),
        ),
        migrations.AddField(
            model_name='data',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='project_structure.Project'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='prepared_by',
            field=models.ManyToManyField(related_name='analysis_prepared_by', to='project_structure.Researcher'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='project_structure.Project'),
        ),
    ]
