# Generated by Django 2.0.3 on 2018-04-02 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_structure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
