# Generated by Django 2.0.3 on 2018-04-03 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_structure', '0002_auto_20180402_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='git_repo',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='shared_drive',
            field=models.URLField(blank=True),
        ),
    ]
