# Generated by Django 2.0.3 on 2018-04-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_structure', '0003_auto_20180403_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='acronym',
            field=models.CharField(default='UMFS', max_length=10),
            preserve_default=False,
        ),
    ]
