# Generated by Django 2.0.3 on 2018-04-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_structure', '0004_project_acronym'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('research_attendees', models.ManyToManyField(to='project_structure.Researcher')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='meetings',
            field=models.ManyToManyField(to='project_structure.Meeting'),
        ),
    ]
