# Generated by Django 2.0.3 on 2018-04-06 20:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project_structure', '0006_auto_20180406_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='meetings',
        ),
        migrations.AddField(
            model_name='meeting',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='project_structure.Project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
