# Generated by Django 2.0.3 on 2018-04-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_structure', '0009_auto_20180406_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='research_attendees',
        ),
        migrations.AddField(
            model_name='meeting',
            name='prepared_by',
            field=models.ManyToManyField(related_name='prepared_by', to='project_structure.Researcher'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='project_attendees',
            field=models.ManyToManyField(related_name='project_attendees', to='project_structure.Researcher'),
        ),
    ]
