# Generated by Django 2.0.3 on 2018-04-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_structure', '0010_auto_20180410_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='title',
            field=models.CharField(default='Default', max_length=200),
            preserve_default=False,
        ),
    ]
