# Generated by Django 2.0.3 on 2018-05-15 19:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project_structure', '0012_researcher_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Literature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('prepared_by', models.ManyToManyField(related_name='literature_prepared_by', to='project_structure.Researcher')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='project_structure.Project')),
            ],
        ),
        migrations.AlterField(
            model_name='meeting',
            name='prepared_by',
            field=models.ManyToManyField(related_name='meeting_prepared_by', to='project_structure.Researcher'),
        ),
    ]
