# Generated by Django 2.0.3 on 2018-05-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications_bootstrap', '0005_auto_20180516_1334'),
        ('project_structure', '0014_auto_20180516_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='literature',
            name='citations',
            field=models.ManyToManyField(related_name='literature_citation', to='publications_bootstrap.Publication'),
        ),
        migrations.AddField(
            model_name='project',
            name='citations',
            field=models.ManyToManyField(blank=True, to='publications_bootstrap.Publication'),
        ),
    ]
