# Generated by Django 2.0.3 on 2018-05-17 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications_bootstrap', '0005_auto_20180516_1334'),
        ('project_structure', '0015_auto_20180517_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('publication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publications_bootstrap.Publication')),
            ],
            bases=('publications_bootstrap.publication',),
        ),
        migrations.AlterField(
            model_name='literature',
            name='citations',
            field=models.ManyToManyField(related_name='literature_citation', to='project_structure.Citation'),
        ),
        migrations.AlterField(
            model_name='project',
            name='citations',
            field=models.ManyToManyField(blank=True, to='project_structure.Citation'),
        ),
    ]
