# Generated by Django 2.0.3 on 2018-05-16 17:34

from django.db import migrations, models
import django.db.models.deletion
import wagtail.contrib.routable_page.models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project_structure', '0014_auto_20180516_1334'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAnalysisPage',
            fields=[
                ('projectnotepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.ProjectNotePage')),
                ('analysis_notes', wagtail.core.fields.RichTextField(blank=True)),
                ('analysis_structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project_structure.Analysis')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'projects.projectnotepage'),
        ),
        migrations.CreateModel(
            name='ProjectDataPage',
            fields=[
                ('projectnotepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.ProjectNotePage')),
                ('data_notes', wagtail.core.fields.RichTextField(blank=True)),
                ('data_structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project_structure.Data')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'projects.projectnotepage'),
        ),
        migrations.CreateModel(
            name='ProjectMiscPage',
            fields=[
                ('projectnotepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.ProjectNotePage')),
                ('misc_notes', wagtail.core.fields.RichTextField(blank=True)),
                ('misc_structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project_structure.Misc')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'projects.projectnotepage'),
        ),
        migrations.CreateModel(
            name='ProjectPublicationPage',
            fields=[
                ('projectnotepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.ProjectNotePage')),
                ('publication_notes', wagtail.core.fields.RichTextField(blank=True)),
                ('publication_structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project_structure.Publication')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'projects.projectnotepage'),
        ),
    ]
