# Generated by Django 2.0.3 on 2018-04-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_structure', '0003_auto_20180403_0235'),
        ('projects', '0007_projectmeetingpage_project_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmeetingpage',
            name='attendees',
            field=models.ManyToManyField(blank=True, to='project_structure.Researcher'),
        ),
    ]
