# Generated by Django 2.0.3 on 2018-04-06 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_projectmeetingpage_attendees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmeetingpage',
            name='attendees',
        ),
    ]
