# Generated by Django 2.0.3 on 2018-04-06 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_structure', '0007_auto_20180406_2028'),
        ('projects', '0009_remove_projectmeetingpage_attendees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmeetingpage',
            name='project_structure',
        ),
        migrations.AddField(
            model_name='projectmeetingpage',
            name='meeting_structure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='project_structure.Meeting'),
            preserve_default=False,
        ),
    ]
