# Generated by Django 2.0.3 on 2018-04-06 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20180406_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmeetingpage',
            name='meeting_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project_structure.Meeting'),
        ),
    ]
