# Generated by Django 2.0.3 on 2018-04-11 16:35

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20180406_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmeetingpage',
            name='meeting_notes',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
