from django.urls import path
from project_structure.views import *
from project_structure.import_bibtex import import_bibtex

urlpatterns = [
    path(r'<int:project>/meeting/add/<int:pageId>', MeetingCreate.as_view(), name='meeting-add'),
    path(r'<int:project>/meeting/<int:pk>/', MeetingUpdate.as_view(), name='meeting-update'),
    path(r'<int:project>/meeting/<int:pk>/delete/', MeetingDelete.as_view(), name='meeting-delete'),
    path(r'<int:project>/meeting/<int:pk>/', MeetingDetail.as_view(), name='meeting-detail'),
    path(r'<int:project>/meetings/', MeetingList.as_view(), name='meeting-list'),
    path(r'<int:project>/literature/add/<int:pageId>', LiteratureCreate.as_view(), name='literature-add'),
    path(r'<int:project>/literature/add-citation/<int:pageId>', import_bibtex, name='literature-import-bibtex'),
    path(r'<int:project>/literature/<int:pk>/', LiteratureUpdate.as_view(), name='literature-update'),
    path(r'<int:project>/literature/<int:pk>/delete/', LiteratureDelete.as_view(), name='literature-delete'),
    path(r'<int:project>/literature/<int:pk>/', LiteratureDetail.as_view(), name='literature-detail'),
    path(r'<int:project>/literatures/', LiteratureList.as_view(), name='literature-list'),
    path(r'<int:project>/data/add/<int:pageId>', DataCreate.as_view(), name='data-add'),
    path(r'<int:project>/data/<int:pk>/', DataUpdate.as_view(), name='data-update'),
    path(r'<int:project>/data/<int:pk>/delete/', DataDelete.as_view(), name='data-delete'),
    path(r'<int:project>/data/<int:pk>/', DataDetail.as_view(), name='data-detail'),
    path(r'<int:project>/datas/', DataList.as_view(), name='data-list'),
    path(r'<int:project>/analysis/add/<int:pageId>', AnalysisCreate.as_view(), name='analysis-add'),
    path(r'<int:project>/analysis/<int:pk>/', AnalysisUpdate.as_view(), name='analysis-update'),
    path(r'<int:project>/analysis/<int:pk>/delete/', AnalysisDelete.as_view(), name='analysis-delete'),
    path(r'<int:project>/analysis/<int:pk>/', AnalysisDetail.as_view(), name='analysis-detail'),
    path(r'<int:project>/analyses/', AnalysisList.as_view(), name='analysis-list'),
    path(r'<int:project>/publication/add/<int:pageId>', PublicationCreate.as_view(), name='publication-add'),
    path(r'<int:project>/publication/<int:pk>/', PublicationUpdate.as_view(), name='publication-update'),
    path(r'<int:project>/publication/<int:pk>/delete/', PublicationDelete.as_view(), name='publication-delete'),
    path(r'<int:project>/publication/<int:pk>/', PublicationDetail.as_view(), name='publication-detail'),
    path(r'<int:project>/publications/', PublicationList.as_view(), name='publication-list'),
    path(r'<int:project>/misc/add/<int:pageId>', MiscCreate.as_view(), name='miscellaneous-add'),
    path(r'<int:project>/misc/<int:pk>/', MiscUpdate.as_view(), name='miscellaneous-update'),
    path(r'<int:project>/misc/<int:pk>/delete/', MiscDelete.as_view(), name='miscellaneous-delete'),
    path(r'<int:project>/misc/<int:pk>/', MiscDetail.as_view(), name='miscellaneous-detail'),
    path(r'<int:project>/miscs/', MiscList.as_view(), name='miscellaneous-list'),
    path(r'researcher/add/', ResearcherCreate.as_view(), name='researcher-add'),
    path(r'researcher/add/<userId>', ResearcherCreate.as_view(), name='researcher-add'),
    path(r'researcher/<int:pk>/', ResearcherUpdate.as_view(), name='researcher-update'),
    path(r'researcher/<int:pk>/delete/', ResearcherDelete.as_view(), name='researcher-delete'),
    path(r'researcher-detail/<int:pk>/', ResearcherDetail.as_view(), name='researcher-detail'),
    path(r'researchers/', ResearcherList.as_view(), name='researcher-list'),
    path(r'sponsor/add/', SponsorCreate.as_view(), name='sponsor-add'),
    path(r'sponsor/<int:pk>/', SponsorUpdate.as_view(), name='sponsor-update'),
    path(r'sponsor/<int:pk>/delete/', SponsorDelete.as_view(), name='sponsor-delete'),
    path(r'sponsor/<int:pk>/', SponsorDetail.as_view(), name='sponsor-detail'),
    path(r'sponsors/', SponsorList.as_view(), name='sponsor-list'),
    path(r'add/<int:pageId>', ProjectCreate.as_view(), name='project-add'),
    path(r'<int:pk>/', ProjectUpdate.as_view(), name='project-update'),
    path(r'<int:pk>/delete/', ProjectDelete.as_view(), name='project-delete'),
    path(r'<int:pk>/', ProjectDetail.as_view(), name='project-detail'),
    path(r'add-list/<int:pk>/', NoteAdd.as_view(), name='add-list'),
    path(r'add-citation/<int:project>/', import_bibtex, name='import-bibtex'),
    path(r'<int:pageId>/citation/<int:pk>/', CitationUpdate.as_view(), name='citation-update'),
    path(r'', ProjectList.as_view(), name='project-list'),
]